context:
  version: "0.0.9"

package:
  name: ducklake-sdk
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/ducklake-sdk/ducklake_sdk-${{ version }}.tar.gz
  sha256: 9899b001e26a6d9c0930cd4138a7c7c9d23629dc949b39ae42c25e2d05c2145d

build:
  number: 1
  skip: is_abi3 and not is_python_min
  python:
    version_independent: ${{ is_abi3 }}
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      # Remove this wrapper once https://github.com/conda-forge/rust-activation-feedstock/pull/79 is merged
      - if: unix
        then:
          - mkdir -p "${BUILD_PREFIX}/bin"
          - cp "${RECIPE_DIR}/cargo-auditable-wrapper.sh" "${BUILD_PREFIX}/bin/cargo-auditable-wrapper"
          - export CARGO="cargo-auditable-wrapper"
        else:
          - copy "%RECIPE_DIR%\cargo-auditable-wrapper.bat" "%BUILD_PREFIX%\bin\cargo-auditable-wrapper.bat" || exit 1
          - set CARGO=cargo-auditable-wrapper
      - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
      - python -m pip install . --no-deps --ignore-installed -vv --no-build-isolation --disable-pip-version-check

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cargo-auditable
  host:
    - python
    - if: is_abi3
      then: python-abi3
    - pip
    - maturin >=1.7,<2
  run:
    - python
    - typing_extensions
  run_constraints:
    - polars >=1.40
    - sqlalchemy >=2

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - '*'
      imports:
        - ducklake
      pip_check: true
  - if: is_abi3
    then:
      script:
        - if: win
          then: abi3audit %PREFIX%/Lib/site-packages/ducklake/_native.pyd -s -v --assume-minimum-abi3 ${{ python_min }}
          else: abi3audit $SP_DIR/ducklake/_native.abi3.so -s -v --assume-minimum-abi3 ${{ python_min }}
      requirements:
        run:
          - abi3audit

about:
  homepage: https://github.com/borchero/ducklake-sdk
  summary: Python SDK to interact with DuckLake.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  documentation: https://ducklake-sdk.readthedocs.io/
  repository: https://github.com/borchero/ducklake-sdk

extra:
  recipe-maintainers:
    - borchero
